### ISSUE TITLE
Zoom issue while sorting

### ISSUE THREAD

**Issue by BSSAbdullah** [tahir-sharif/sortable-draggable-js#2]
sortable does not work properly when passing parent element as zoomEelement or passing zoom value

**Comment by tahir-sharif** [comment]
Hi @BSSAbdullah ,

Thank you for bringing up the issue regarding sortable not working properly when passing a parent element as `zoomElement` or using a `zoom` value.

I’ve resolved the problem, and the fix is now available. You can update the package using the following command:

```bash
npm update sortable-draggable-js
```

After updating, you should be able to pass `zoomElement` or use a `zoom` value without any issues. If you experience any further problems or have additional feedback, feel free to reach out. I appreciate your support and patience!

Best regards,
Tahir
